/**
 * Central icon module — the ONLY place the app imports icons from directly
 * (besides this file re-exporting). Every icon used anywhere in the app,
 * including inside the shadcn/ui primitives, is sourced from
 * @tabler/icons-react and re-exported here under the names the rest of the
 * codebase already uses, so call sites never need to know the underlying
 * icon set.
 */

export type { TablerIcon as LucideIcon } from "@tabler/icons-react";

// Direct 1:1 name matches (Tabler ships "Icon" + the same word).
export {
  IconActivity as Activity,
  IconArchive as Archive,
  IconArrowDown as ArrowDown,
  IconArrowLeft as ArrowLeft,
  IconArrowRight as ArrowRight,
  IconArrowUp as ArrowUp,
  IconBan as Ban,
  IconBell as Bell,
  IconBox as Box,
  IconCalendarClock as CalendarClock,
  IconCheck as Check,
  IconCheck as CheckIcon,
  IconChevronDown as ChevronDown,
  IconChevronDown as ChevronDownIcon,
  IconChevronLeft as ChevronLeft,
  IconChevronRight as ChevronRight,
  IconChevronRight as ChevronRightIcon,
  IconChevronUp as ChevronUpIcon,
  IconChevronsLeft as ChevronsLeft,
  IconCircleCheck as CircleCheck,
  IconCircleCheck as CircleCheckIcon,
  IconCircleDashed as CircleDashed,
  IconCircleOff as CircleOff,
  IconCirclePlus as CirclePlus,
  IconCopy as Copy,
  IconCpu as Cpu,
  IconDatabase as Database,
  IconDownload as Download,
  IconExternalLink as ExternalLink,
  IconEye as Eye,
  IconEyeOff as EyeOff,
  IconFile as File,
  IconFileCode as FileCode,
  IconFilePlus as FilePlus,
  IconFileText as FileText,
  IconFolder as Folder,
  IconFolderOpen as FolderOpen,
  IconFolderPlus as FolderPlus,
  IconGauge as Gauge,
  IconWorld as Globe,
  IconHash as Hash,
  IconHeart as Heart,
  IconHelpCircle as HelpCircle,
  IconLayoutDashboard as LayoutDashboard,
  IconKeyboard as Keyboard,
  IconLoader2 as Loader2,
  IconLoader2 as Loader2Icon,
  IconMail as Mail,
  IconMapPin as MapPin,
  IconMenu2 as Menu,
  IconMoon as Moon,
  IconNavigation as Navigation,
  IconNetwork as Network,
  IconPalette as Palette,
  IconPencil as Pencil,
  IconPlus as Plus,
  IconPower as Power,
  IconRouter as Router,
  IconSearch as Search,
  IconSearch as SearchIcon,
  IconServer as Server,
  IconSettings as Settings,
  IconShield as Shield,
  IconShieldCheck as ShieldCheck,
  IconShirt as Shirt,
  IconSquare as Square,
  IconStar as Star,
  IconSun as Sun,
  IconTerminal2 as Terminal,
  IconUpload as Upload,
  IconUser as User,
  IconUserPlus as UserPlus,
  IconUserX as UserX,
  IconUsers as Users,
  IconWebhook as Webhook,
  IconX as X,
  IconX as XIcon,
} from "@tabler/icons-react";

// Names where Tabler uses a different word — mapped by closest visual/semantic match.
export {
  IconArrowBarToDown as ArrowDownToLine,
  IconChecks as CheckCheck,
  IconSelector as ChevronsUpDown,
  IconAlertCircle as CircleAlert,
  IconFileZip as FileArchive,
  IconJson as FileJson,
  IconShoe as Footprints,
  IconServer2 as HardDrive,
  IconHelmet as HardHat,
  IconInfoCircle as Info,
  IconInfoCircle as InfoIcon,
  IconKey as KeyRound,
  IconPlaylistAdd as ListPlus,
  IconPlaylistX as ListX,
  IconLogout as LogOut,
  IconMaximize as Maximize2,
  IconStack2 as MemoryStick,
  IconMessage as MessageSquare,
  IconMinimize as Minimize2,
  IconDeviceDesktop as Monitor,
  IconDots as MoreHorizontal,
  IconDots as MoreHorizontalIcon,
  IconDotsVertical as MoreVertical,
  IconArrowsMove as Move,
  IconAlertOctagon as OctagonXIcon,
  IconPackage as PackageCheck,
  IconPackageOff as PackageX,
  IconPlayerPause as Pause,
  IconPlayerPause as PauseCircle,
  IconPlayerPlay as Play,
  IconPlugOff as PowerOff,
  IconRefresh as RefreshCw,
  IconRotate as RotateCcw,
  IconRotateClockwise as RotateCw,
  IconDeviceFloppy as Save,
  IconLogs as ScrollText,
  IconShieldX as ShieldBan,
  IconDeviceMobile as Smartphone,
  IconStopwatch as Timer,
  IconTrash as Trash2,
  IconAlertTriangle as TriangleAlert,
  IconAlertTriangle as TriangleAlertIcon,
  IconBolt as Zap,
} from "@tabler/icons-react";
