/**
 * Server icons: a curated, tree-shakeable set of ~90 Tabler icons used for
 * the fast synchronous path (rendering an already-assigned icon anywhere in
 * the app — server lists, headers, nav diagrams, ...). Using named imports
 * here (rather than a namespace import of the whole package) keeps this
 * module — which `ServerBlockIcon` pulls into nearly every page — small.
 *
 * The full, searchable 6000+ icon set used by the icon *picker* UI lives in
 * `server-icon-search.ts`, a separate module loaded lazily so its weight
 * only ever lands on pages that actually render the picker.
 */
import type { TablerIcon } from "@tabler/icons-react";
import {
  IconServer2,
  IconTrees,
  IconTree,
  IconBuildingCommunity,
  IconBuildingCastle,
  IconPalette,
  IconFlask,
  IconDeviceGamepad2,
  IconRouter,
  IconAntenna,
  IconSword,
  IconPick,
  IconDiamond,
  IconFlame,
  IconSnowflake,
  IconSkull,
  IconGhost,
  IconBolt,
  IconRocket,
  IconCrown,
  IconShield,
  IconMap,
  IconCompass,
  IconAnchor,
  IconMushroom,
  IconCactus,
  IconBone,
  IconEgg,
  IconFish,
  IconSpider,
  IconSun,
  IconMoon,
  IconStar,
  IconHeart,
  IconLeaf,
  IconApple,
  IconCarrot,
  IconBread,
  IconMeat,
  IconPizza,
  IconCoffee,
  IconBeer,
  IconMusic,
  IconBook,
  IconKey,
  IconLock,
  IconBell,
  IconGift,
  IconCamera,
  IconHome,
  IconTower,
  IconMountain,
  IconDroplet,
  IconCloudRain,
  IconRainbow,
  IconCat,
  IconDog,
  IconButterfly,
  IconBug,
  IconFeather,
  IconPawFilled,
  IconBat,
  IconDeer,
  IconChristmasTree,
  IconBalloon,
  IconConfetti,
  IconAward,
  IconTrophy,
  IconTarget,
  IconChess,
  IconDice,
  IconPuzzle,
  IconWand,
  IconMeteor,
  IconPlanet,
  IconAtom,
  IconFlag,
  IconSwords,
  IconShieldCheck,
  IconHammer,
  IconAxe,
  IconBow,
  IconWall,
  IconFence,
  IconDoor,
  IconStairs,
  IconTelescope,
  IconBinoculars,
  IconCampfire,
  IconTent,
  IconBackpack,
  IconBarrel,
  IconCoin,
} from "@tabler/icons-react";

const STATIC_ICON_MAP: Record<string, TablerIcon> = {
  Server2: IconServer2,
  Trees: IconTrees,
  Tree: IconTree,
  BuildingCommunity: IconBuildingCommunity,
  BuildingCastle: IconBuildingCastle,
  Palette: IconPalette,
  Flask: IconFlask,
  DeviceGamepad2: IconDeviceGamepad2,
  Router: IconRouter,
  Antenna: IconAntenna,
  Sword: IconSword,
  Pick: IconPick,
  Diamond: IconDiamond,
  Flame: IconFlame,
  Snowflake: IconSnowflake,
  Skull: IconSkull,
  Ghost: IconGhost,
  Bolt: IconBolt,
  Rocket: IconRocket,
  Crown: IconCrown,
  Shield: IconShield,
  Map: IconMap,
  Compass: IconCompass,
  Anchor: IconAnchor,
  Mushroom: IconMushroom,
  Cactus: IconCactus,
  Bone: IconBone,
  Egg: IconEgg,
  Fish: IconFish,
  Spider: IconSpider,
  Sun: IconSun,
  Moon: IconMoon,
  Star: IconStar,
  Heart: IconHeart,
  Leaf: IconLeaf,
  Apple: IconApple,
  Carrot: IconCarrot,
  Bread: IconBread,
  Meat: IconMeat,
  Pizza: IconPizza,
  Coffee: IconCoffee,
  Beer: IconBeer,
  Music: IconMusic,
  Book: IconBook,
  Key: IconKey,
  Lock: IconLock,
  Bell: IconBell,
  Gift: IconGift,
  Camera: IconCamera,
  Home: IconHome,
  Tower: IconTower,
  Mountain: IconMountain,
  Droplet: IconDroplet,
  CloudRain: IconCloudRain,
  Rainbow: IconRainbow,
  Cat: IconCat,
  Dog: IconDog,
  Butterfly: IconButterfly,
  Bug: IconBug,
  Feather: IconFeather,
  PawFilled: IconPawFilled,
  Bat: IconBat,
  Deer: IconDeer,
  ChristmasTree: IconChristmasTree,
  Balloon: IconBalloon,
  Confetti: IconConfetti,
  Award: IconAward,
  Trophy: IconTrophy,
  Target: IconTarget,
  Chess: IconChess,
  Dice: IconDice,
  Puzzle: IconPuzzle,
  Wand: IconWand,
  Meteor: IconMeteor,
  Planet: IconPlanet,
  Atom: IconAtom,
  Flag: IconFlag,
  Swords: IconSwords,
  ShieldCheck: IconShieldCheck,
  Hammer: IconHammer,
  Axe: IconAxe,
  Bow: IconBow,
  Wall: IconWall,
  Fence: IconFence,
  Door: IconDoor,
  Stairs: IconStairs,
  Telescope: IconTelescope,
  Binoculars: IconBinoculars,
  Campfire: IconCampfire,
  Tent: IconTent,
  Backpack: IconBackpack,
  Barrel: IconBarrel,
  Coin: IconCoin,
};

export const DEFAULT_SERVER_ICON = "Server2";

export const FEATURED_SERVER_ICONS = Object.keys(STATIC_ICON_MAP);

/**
 * Synchronous resolver for the fast path. Falls back to the default icon for
 * any key outside the curated set (e.g. a rarely-picked icon from the full
 * search) — `getServerIconAsync` (in `server-icon-search.ts`) resolves those.
 */
export function getServerIcon(name: string | undefined | null): TablerIcon {
  if (!name) return STATIC_ICON_MAP[DEFAULT_SERVER_ICON];
  return STATIC_ICON_MAP[name] ?? STATIC_ICON_MAP[DEFAULT_SERVER_ICON];
}

export function isCuratedServerIcon(name: string): boolean {
  return name in STATIC_ICON_MAP;
}

/** Splits a PascalCase icon key into readable words, e.g. "DeviceGamepad2" -> "Device Gamepad 2". */
export function humanizeIconName(name: string): string {
  return name.replace(/([a-z])([A-Z])/g, "$1 $2").replace(/([A-Za-z])(\d)/g, "$1 $2");
}
