package orchestrator

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/cometa-mccore/mccore/services/agent/internal/protocol"
)

// writeEula writes eula.txt with the timestamp of acceptance recorded in a
// comment — the actual acceptance record (who/when) lives in the Control
// Plane's EulaAcceptance table (§23); this file only needs to exist and
// say `eula=true` for the server to start, and it is only ever written
// `true` because ServerInstallPayload.EulaAccepted is a literal `true` in
// the wire schema — there is no code path that reaches here without it.
func writeEula(serverDir string) error {
	content := "# Generated by mcCore. EULA acceptance is recorded in the Control Plane audit log.\neula=true\n"
	return os.WriteFile(filepath.Join(serverDir, "eula.txt"), []byte(content), 0644)
}

// writeServerProperties generates server.properties for Vanilla/Paper/
// Purpur/Fabric/Forge/NeoForge-family servers from the install payload.
// Existing values (if server.properties already exists, e.g. a reinstall
// over a preserved world) are preserved for any key this function doesn't
// explicitly manage, so it never clobbers manual tweaks an admin made
// through the file manager.
func writeServerProperties(serverDir string, p protocol.ServerInstallPayload) error {
	path := filepath.Join(serverDir, "server.properties")
	existing := map[string]string{}
	if data, err := os.ReadFile(path); err == nil {
		existing = parseProperties(string(data))
	}

	managed := map[string]string{
		"server-port":          strconv.Itoa(p.Port),
		"max-players":          strconv.Itoa(p.MaxPlayers),
		"online-mode":          strconv.FormatBool(p.OnlineMode),
		"white-list":           strconv.FormatBool(p.Whitelist),
		"pvp":                  strconv.FormatBool(p.PVP),
		"enable-command-block": strconv.FormatBool(p.CommandBlocks),
		"difficulty":           p.Difficulty,
		"gamemode":             p.GameMode,
		"enable-query":         "false",
		"enable-rcon":          "false",
	}
	if p.MOTD != "" {
		// Minecraft's own server.properties parser turns a literal `\n`
		// (backslash + n, not a real newline byte) into the second line of
		// the server-list MOTD — a real newline byte here would instead
		// corrupt this file's own naive line-based format (parseProperties/
		// serializeProperties do no escaping), so it's the escaped form that
		// gets written, never the raw one.
		managed["motd"] = strings.ReplaceAll(p.MOTD, "\n", `\n`)
	}
	for k, v := range managed {
		existing[k] = v
	}
	// A few sane defaults only applied on first creation (never overwritten
	// on reinstall), so an admin's later edits to these via the file
	// manager survive plugin updates / server reinstalls.
	firstTimeDefaults := map[string]string{
		"level-name":          "world",
		"motd":                "A Minecraft Server managed by mcCore",
		"spawn-protection":    "0",
		"generate-structures": "true",
		"view-distance":       "10",
	}
	for k, v := range firstTimeDefaults {
		if _, exists := existing[k]; !exists {
			existing[k] = v
		}
	}

	return os.WriteFile(path, []byte(serializeProperties(existing)), 0644)
}

func parseProperties(content string) map[string]string {
	out := map[string]string{}
	for _, line := range strings.Split(content, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		eq := strings.IndexByte(line, '=')
		if eq < 0 {
			continue
		}
		out[strings.TrimSpace(line[:eq])] = strings.TrimSpace(line[eq+1:])
	}
	return out
}

func serializeProperties(props map[string]string) string {
	var b strings.Builder
	b.WriteString("# Generated/managed by mcCore\n")
	for k, v := range props {
		fmt.Fprintf(&b, "%s=%s\n", k, v)
	}
	return b.String()
}

// writeVelocityConfig writes a minimal velocity.toml for a fresh Velocity
// proxy install. Velocity has no server.properties/eula concept — it's a
// proxy, not a world server (§21 lists it as supported software precisely
// because networks/proxying is a first-class feature, §41).
func writeVelocityConfig(serverDir string, p protocol.ServerInstallPayload) error {
	path := filepath.Join(serverDir, "velocity.toml")
	if _, err := os.Stat(path); err == nil {
		return nil // preserve an existing config (e.g. reinstall) rather than clobbering proxy routing an admin configured by hand
	}
	content := fmt.Sprintf(`config-version = "2.7"
bind = "0.0.0.0:%d"
motd = "<#09add3>A Velocity Proxy managed by mcCore"
show-max-players = %d
online-mode = %t
player-info-forwarding-mode = "modern"

[servers]

[forced-hosts]

[advanced]
compression-threshold = 256
compression-level = -1
login-ratelimit = 3000
connection-timeout = 5000
read-timeout = 30000
`, p.Port, p.MaxPlayers, p.OnlineMode)
	return os.WriteFile(path, []byte(content), 0644)
}
