import { z } from "zod";

/**
 * Stable machine-readable error codes. The frontend maps these to specific
 * user-facing copy (see apps web `src/lib/error-messages.ts`); never show
 * `error.message` from an unmapped code verbatim in production UI, and
 * never forward stack traces to the client (§49/§79).
 */
export const ErrorCode = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  IDEMPOTENCY_KEY_REUSED: "IDEMPOTENCY_KEY_REUSED",

  SETUP_ALREADY_COMPLETE: "SETUP_ALREADY_COMPLETE",
  BOOTSTRAP_CODE_INVALID: "BOOTSTRAP_CODE_INVALID",
  BOOTSTRAP_CODE_EXPIRED: "BOOTSTRAP_CODE_EXPIRED",
  BOOTSTRAP_CODE_USED: "BOOTSTRAP_CODE_USED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  PASSWORD_TOO_WEAK: "PASSWORD_TOO_WEAK",
  TOTP_REQUIRED: "TOTP_REQUIRED",
  TOTP_INVALID: "TOTP_INVALID",

  SERVER_NOT_FOUND: "SERVER_NOT_FOUND",
  SERVER_NOT_RUNNING: "SERVER_NOT_RUNNING",
  SERVER_ALREADY_RUNNING: "SERVER_ALREADY_RUNNING",
  SERVER_BUSY: "SERVER_BUSY",
  PORT_ALREADY_ALLOCATED: "PORT_ALREADY_ALLOCATED",
  EULA_NOT_ACCEPTED: "EULA_NOT_ACCEPTED",

  NODE_NOT_FOUND: "NODE_NOT_FOUND",
  NODE_OFFLINE: "NODE_OFFLINE",
  NODE_UNAVAILABLE: "NODE_UNAVAILABLE",
  ENROLLMENT_TOKEN_INVALID: "ENROLLMENT_TOKEN_INVALID",
  ENROLLMENT_TOKEN_EXPIRED: "ENROLLMENT_TOKEN_EXPIRED",
  ENROLLMENT_TOKEN_USED: "ENROLLMENT_TOKEN_USED",
  AGENT_AUTH_INVALID: "AGENT_AUTH_INVALID",
  AGENT_PROTOCOL_INCOMPATIBLE: "AGENT_PROTOCOL_INCOMPATIBLE",

  INSUFFICIENT_DISK_SPACE: "INSUFFICIENT_DISK_SPACE",
  JAVA_RUNTIME_UNAVAILABLE: "JAVA_RUNTIME_UNAVAILABLE",
  DOWNLOAD_FAILED: "DOWNLOAD_FAILED",
  PATH_TRAVERSAL_REJECTED: "PATH_TRAVERSAL_REJECTED",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",

  BACKUP_NOT_FOUND: "BACKUP_NOT_FOUND",
  BACKUP_IN_PROGRESS: "BACKUP_IN_PROGRESS",
  RESTORE_IN_PROGRESS: "RESTORE_IN_PROGRESS",

  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const ErrorResponseSchema = z.object({
  error: z.object({
    code: z.string(),
    message: z.string(),
    requestId: z.string(),
    details: z.record(z.string(), z.unknown()).optional(),
  }),
});

export type ErrorResponse = z.infer<typeof ErrorResponseSchema>;

const STATUS_BY_CODE: Partial<Record<ErrorCode, number>> = {
  VALIDATION_ERROR: 400,
  UNAUTHENTICATED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  RATE_LIMITED: 429,
  IDEMPOTENCY_KEY_REUSED: 409,
  SETUP_ALREADY_COMPLETE: 409,
  BOOTSTRAP_CODE_INVALID: 401,
  BOOTSTRAP_CODE_EXPIRED: 401,
  BOOTSTRAP_CODE_USED: 401,
  INVALID_CREDENTIALS: 401,
  ACCOUNT_SUSPENDED: 403,
  PASSWORD_TOO_WEAK: 400,
  TOTP_REQUIRED: 401,
  TOTP_INVALID: 401,
  SERVER_NOT_FOUND: 404,
  SERVER_NOT_RUNNING: 409,
  SERVER_ALREADY_RUNNING: 409,
  SERVER_BUSY: 409,
  PORT_ALREADY_ALLOCATED: 409,
  EULA_NOT_ACCEPTED: 400,
  NODE_NOT_FOUND: 404,
  NODE_OFFLINE: 409,
  NODE_UNAVAILABLE: 503,
  ENROLLMENT_TOKEN_INVALID: 401,
  ENROLLMENT_TOKEN_EXPIRED: 401,
  ENROLLMENT_TOKEN_USED: 401,
  AGENT_AUTH_INVALID: 401,
  AGENT_PROTOCOL_INCOMPATIBLE: 409,
  INSUFFICIENT_DISK_SPACE: 507,
  JAVA_RUNTIME_UNAVAILABLE: 409,
  DOWNLOAD_FAILED: 502,
  PATH_TRAVERSAL_REJECTED: 400,
  FILE_TOO_LARGE: 413,
  BACKUP_NOT_FOUND: 404,
  BACKUP_IN_PROGRESS: 409,
  RESTORE_IN_PROGRESS: 409,
  INTERNAL_ERROR: 500,
};

export function httpStatusForErrorCode(code: string): number {
  return STATUS_BY_CODE[code as ErrorCode] ?? 500;
}

export class ApiError extends Error {
  code: ErrorCode;
  details?: Record<string, unknown>;

  constructor(code: ErrorCode, message: string, details?: Record<string, unknown>) {
    super(message);
    this.name = "ApiError";
    this.code = code;
    this.details = details;
  }

  get status(): number {
    return httpStatusForErrorCode(this.code);
  }
}
